name: 'Daily auto-merge with PAT'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # daily
    # - cron:  '0 0 * * *'
    # hourly at xx:50 time intervals, replace 50 with your desired minute
    - cron:  '50 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: zoltndor/tudas-tar
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'zoltdor'
          git config --global user.email 'zoltndor@yahoo.co.uk'

      - name: Merge and push
        run: |
          git fetch origin master:master
          git checkout master
          git merge main --no-ff -m "Merge main to master"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/zoltndor/tudas-tar.git master
